### ISSUE TITLE
Module issues

### ISSUE THREAD

**Issue by Kediel** [Kediel/BHP#2]
[*] Setting up en1
Traceback (most recent call last):
File "arper.py", line 80, in <module>
    gateway_mac = get_mac(gateway_ip)
File "arper.py", line 30, in get_mac
    timeout = 2, retry = 10)
File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 377, in srp
    s = conf.L2socket(iface=iface, filter=filter, nofilter=nofilter, type=type)
File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 432, in __init__
    set_promisc(self.ins, self.iface)
File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 160, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, "")
File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 292, in get_if_index
    return int(struct.unpack("I",get_if(iff, SIOCGIFINDEX)[16:20])[0])
File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 19, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff))
IOError: [Errno 19] No such device

**Comment by Kediel** [comment]
Changed the interface to en0 (the correct interface). However, getting the same error.

**Comment by Kediel** [comment]
Commented out the conf.iface line. Corrected this issue.
